//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudGenerator.Core.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrudGenerator.Core.Wpf.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string ColumnDefaultValue {
            get {
                return ResourceManager.GetString("ColumnDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Type.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name: .
        /// </summary>
        internal static string DatabaseNameTitle {
            get {
                return ResourceManager.GetString("DatabaseNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Path: .
        /// </summary>
        internal static string DatabasePathTitle {
            get {
                return ResourceManager.GetString("DatabasePathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type: .
        /// </summary>
        internal static string DatabaseTypeTitle {
            get {
                return ResourceManager.GetString("DatabaseTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Values.
        /// </summary>
        internal static string DefaultValues {
            get {
                return ResourceManager.GetString("DefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to open database:
        ///{0}.
        /// </summary>
        internal static string ErrorOnOpenSqliteDatabase {
            get {
                return ResourceManager.GetString("ErrorOnOpenSqliteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Column.
        /// </summary>
        internal static string ForeignColumn {
            get {
                return ResourceManager.GetString("ForeignColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Columns.
        /// </summary>
        internal static string ForeignColumns {
            get {
                return ResourceManager.GetString("ForeignColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Keys.
        /// </summary>
        internal static string ForeignKeys {
            get {
                return ResourceManager.GetString("ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed Columns.
        /// </summary>
        internal static string IndexedColumns {
            get {
                return ResourceManager.GetString("IndexedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        internal static string Indexes {
            get {
                return ResourceManager.GetString("Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Name.
        /// </summary>
        internal static string IndexName {
            get {
                return ResourceManager.GetString("IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Unique.
        /// </summary>
        internal static string IsIndexUnique {
            get {
                return ResourceManager.GetString("IsIndexUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary Key.
        /// </summary>
        internal static string IsPrimaryKeyColumn {
            get {
                return ResourceManager.GetString("IsPrimaryKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql Database Connection Configuration.
        /// </summary>
        internal static string MySqlDatabaseConnectionConfiguration {
            get {
                return ResourceManager.GetString("MySqlDatabaseConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        internal static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSql Database Connection Configuration.
        /// </summary>
        internal static string PostgreSqlDatabaseConnectionConfiguration {
            get {
                return ResourceManager.GetString("PostgreSqlDatabaseConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Database Informations.
        /// </summary>
        internal static string ReadDatabaseInformations {
            get {
                return ResourceManager.GetString("ReadDatabaseInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced Column.
        /// </summary>
        internal static string ReferencedColumn {
            get {
                return ResourceManager.GetString("ReferencedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced Table.
        /// </summary>
        internal static string ReferencedTable {
            get {
                return ResourceManager.GetString("ReferencedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Database Name....
        /// </summary>
        internal static string SelectedDatabaseName {
            get {
                return ResourceManager.GetString("SelectedDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password....
        /// </summary>
        internal static string SelectedPassword {
            get {
                return ResourceManager.GetString("SelectedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Server Name or Server IP Addres....
        /// </summary>
        internal static string SelectedServerOrIpAddress {
            get {
                return ResourceManager.GetString("SelectedServerOrIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected the Sqlite Database File....
        /// </summary>
        internal static string SelectedSqliteDatabaseFile {
            get {
                return ResourceManager.GetString("SelectedSqliteDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected the Database Type.
        /// </summary>
        internal static string SelectedTheDatabaseTypeTitle {
            get {
                return ResourceManager.GetString("SelectedTheDatabaseTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the User ID....
        /// </summary>
        internal static string SelectedUserId {
            get {
                return ResourceManager.GetString("SelectedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the database type to proceed....
        /// </summary>
        internal static string SelectTheDatabase {
            get {
                return ResourceManager.GetString("SelectTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: .
        /// </summary>
        internal static string ServerTitle {
            get {
                return ResourceManager.GetString("ServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sqlite Database Connection Configuration.
        /// </summary>
        internal static string SqliteDatabaseConnectionConfiguration {
            get {
                return ResourceManager.GetString("SqliteDatabaseConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServer Database Connection Configuration.
        /// </summary>
        internal static string SqlServerDatabaseConnectionConfiguration {
            get {
                return ResourceManager.GetString("SqlServerDatabaseConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Definitions.
        /// </summary>
        internal static string TableDefinitions {
            get {
                return ResourceManager.GetString("TableDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID: .
        /// </summary>
        internal static string UserIdTitle {
            get {
                return ResourceManager.GetString("UserIdTitle", resourceCulture);
            }
        }
    }
}
